version: '3.8'

services:
  web: &app
    build:
      context: .
    image: spotlight
    stdin_open: true
    tty: true
    user: root
    env_file:
      - .env
    environment:
      - VIRTUAL_PORT=3000
      - VIRTUAL_HOST=.spotlight.test
    depends_on:
      - postgres
      - db_migrate
      - solr
    ports:
      - 3000:3000
    volumes:
      - .:/app/spotlight
    networks:
      internal:

  db_migrate:
    image: spotlight
    env_file:
      - .env
    entrypoint: ["sh", "-c"]
    command:
      - bin/db-wait.sh postgres:5432 bundle exec rake db:migrate
    depends_on:
      - postgres
    volumes:
      - .:/app/spotlight
    networks:
      internal:

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=spotlight_user
      - POSTGRES_PASSWORD=spotlight_password
      - POSTGRES_DB=spotlight
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      internal:

  redis:
    image: bitnami/redis:6.2
    command: redis-server --protected-mode no --stop-writes-on-bgsave-error no
    volumes:
      - redis:/data
    networks:
      internal:

  solr:
    image: solr:8.8
    env_file:
      - .env
    ports:
      - 8983:8983
    networks:
      internal:
    command:
      - sh
      - "-c"
      - "solr-precreate spotlight /opt/solr/server/configsets/spotlightconf"
    volumes:
      - solr_home:/var/solr/data:cached
      - ./solr/conf:/opt/solr/server/configsets/spotlightconf

volumes:
  db:
  redis:
  solr_home:

networks:
      internal:
