apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spotlight.fullname" . }}-env
  labels:
    {{- include "spotlight.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ template "spotlight.externalPostgresql.database" . }}
  POSTGRES_HOST: {{ template "spotlight.externalPostgresql.host" . }}
  POSTGRES_PORT: "5432"
  POSTGRES_USER: {{ include "spotlight.externalPostgresql.username" . | quote }}
  RAILS_ENV: production
  {{- if .Values.redis.enabled }}
  REDIS_HOST: {{ template "hyrax.redis.host" . }}
  {{- end }}
  SOLR_ADMIN_USER: {{ template "spotlight.solr.username" . }}
  SOLR_COLLECTION_NAME: {{ template "spotlight.solr.collectionName" . }}
  SOLR_CONFIGSET_NAME: {{ template "spotlight.fullname" . }}
  SOLR_HOST: {{ template "spotlight.solr.host" . }}
  SOLR_PORT: "8983"
  SOLR_URL: {{ template "spotlight.solr.url" . }}
{{- range $key, $value := .Values.env.configmap }}
  {{ $key }}: "{{ $value }}"
{{- end }}
