{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "spotlight.fullname" . }}-uploads
  labels:
    {{- include "spotlight.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.shared.uploadStorage.size }}
  {{- if .Values.shared.uploadStorage.className }}
  storageClassName: "{{ .Values.shared.uploadStorage.className }}"
  {{- end }}
{{- end }}
