apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spotlight.fullname" . }}
  labels:
    {{- include "spotlight.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ include "spotlight.postgresql.password" . | b64enc | quote }}
  SECRET_KEY_BASE: {{ randAlphaNum 20 | b64enc | quote }}
  {{- if not .Values.solrExistingSecret }}
  SOLR_ADMIN_PASSWORD: {{ include "spotlight.solr.password" . | b64enc }}
  {{- end }}
  {{- if .Values.redis.enabled }}
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc}}
  SIDEKIQ_REDIS_URL: {{ include "hyrax.redis.url" . | b64enc }}
  {{- end }}
{{- range $key, $value := .Values.env.secret }}
  {{ $key }}: {{ $value |b64enc }}
{{- end }}