replicaCount: 1

imagePullSecrets:
  - name: gitlab-registry

persistence:
  enabled: true

shared:
  uploadStorage:
    size: 10Gi
    className: nfs

podSecurityContext:
  runAsUser: 1001
  runAsGroup: 101
  fsGroup: 101
  fsGroupChangePolicy: "OnRootMismatch"

ingress:
  enabled: true
  hosts:
    - host: staging-harvard-curiosity.notch8.cloud
      paths:
        - path: /
  annotations: {
    kubernetes.io/ingress.class: "nginx",
    nginx.ingress.kubernetes.io/proxy-body-size: "0",
    cert-manager.io/cluster-issuer: letsencrypt-prod
  }
  tls:
    - hosts:
        - staging-harvard-curiosity.notch8.cloud
      secretName: notch8cloud

postgresql:
  enabled: false
  persistence:
    size: 100Gi
externalPostgresql:
  host: pg-postgresql.staging-postgres.svc.cluster.local
  username: postgres
  password: $PG_PASSWORD

fcrepo:
  enabled: false
externalFcrepoHost: fcrepo.staging-fcrepo.svc.cluster.local

solr:
  enabled: false
externalSolrPassword: $SOLR_PASSWORD
externalSolrHost: solr.staging-solr.svc.cluster.local
externalSolrUser: admin
externalSolrCollection: "spotlight"

env:
  configmap:
    APP_HOST: staging-harvard-curiosity.notch8.cloud
    SENTRY_DSN: $SENTRY_DSN
